### ISSUE TITLE
ModuleNotFoundError: No module named 'itkHelpers'

### ISSUE THREAD

**Issue by dyollb** [InsightSoftwareConsortium/ITKLabelErodeDilate#36]
Hi,

In C++ I like to use the `LabelSet[Dilate|Erode]ImageFilter` for dilating/eroding multi-label images.
Unfortunately, the python module fails for following code:
```
dilate = itk.LabelSetDilateImageFilter.New(image, Radius=5.0, UseImageSpacing=True)
```
with following error:
```
Traceback (most recent call last):
  File "/Users/ABC/xzy/split_label.py", line 39, in <module>
    split_label(file_path=input_file)
  File "/Users/ABC/xzy/split_label.py", line 20, in split_label
    dilate = itk.LabelSetDilateImageFilter.New(components, Radius=5.0, UseImageSpacing=True)
  File "/Users/ABCxzy/.venv/lib/python3.9/site-packages/itk/support/lazy.py", line 137, in __getattribute__
    base.itk_load_swig_module(module, namespace)
  File "/Users/ABC/xzy/.venv/lib/python3.9/site-packages/itk/support/base.py", line 110, in itk_load_swig_module
    l_module = loader.load(swig_module_name)
  File "/Users/ABC/xzy/.venv/lib/python3.9/site-packages/itk/support/base.py", line 259, in load
    l_spec.loader.exec_module(l_module)  # pytype: disable=attribute-error
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/ABC/xzy/.venv/lib/python3.9/site-packages/itk/support/../LabelErodeDilatePython.py", line 71, in <module>
    from itk.itkLabelSetDilateImageFilterPython import *
  File "/Users/ABC/xzy/.venv/lib/python3.9/site-packages/itk/itkLabelSetDilateImageFilterPython.py", line 78, in <module>
    import itk.itkLabelSetMorphBaseImageFilterPython
  File "/Users/ABC/xzy/.venv/lib/python3.9/site-packages/itk/itkLabelSetMorphBaseImageFilterPython.py", line 1239, in <module>
    import itkHelpers
ModuleNotFoundError: No module named 'itkHelpers'
```

I am using Python3.9 on MacOS (Intel).
- I tried a clean venv with: `pip install itk-labelerodedilate==1.1.1`
- I also tried the ITK version that was released in the same month: `pip install itk==5.3rc2.post1`

**Comment by dyollb** [comment]
(Possible unrelated) The pythonic API doesn't seem to be available for the same installation:
```
result = itk.labelset_dilate_image_filter(image, radius=5.0, use_image_spacing=True)
```
which results in:
> AttributeError: module 'itk' has no attribute 'labelset_dilate_image_filter'

**Comment by dyollb** [comment]
I see this issue came up in for other remote modules, e.g. [here](https://github.com/SimonRit/RTK/issues/422). The workaround is to use ITK 5.1.2:
```
pip install itk==5.1.2 itk-labelerodedilate --force-reinstall
```
I guess this should be part of the requirements.

**Comment by dzenanz** [comment]
Contributions are welcome. Especially if you use this module often.

**Comment by dyollb** [comment]
I think the error is in an auto-generated file. A new build based on current ITK source and release on pypi probably would fix it. I am happy to help, but i think i can't trigger a build/release the wheel.

**Comment by dzenanz** [comment]
I don't see "releases" in GitHub interface for this repository, even though the action exists. Maybe the tag [1.1.1](https://pypi.org/project/itk-labelerodedilate/1.1.1/) hasn't been pushed to this repository.

**Comment by dzenanz** [comment]
I created a new tag, `v1.2.0`. Let's see if GitHub actions publish a new package automatically.

**Comment by dzenanz** [comment]
The [package](https://pypi.org/project/itk-labelerodedilate/1.2.0/) was published without an issue.

**Comment by dzenanz** [comment]
@dyollb can you try now? Close this issue if it works.

**Comment by dyollb** [comment]
thanks, that fixes it.
